#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

void drive();

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}



task main()
{
  initializeRobot();

  waitForStart();   // wait for start of tele-op phase

  while (true)
  {
	  drive();
  }
}

//Our main driving Function
void drive()
{

	getJoystickSettings(joystick); // update buttons and joysticks
	//motor values equal the joystick Y values
	motor[Left] = joystick.joy1_y1;
	motor[Right] = joystick.joy1_y2;

/* EXAMPLE USE OF BUTTON

	if(joy1Btn(1) == 1)
	{
		// turn a motors power on or off
		motor[intake] = intakePowerLevel++;
	}
	else
	{
		intakePowerLevel = 0;
		motor[intake] = intakePowerLevel;
	}
	*/
}
